name: auth-service
type: containerapp
location: brazilsouth
properties:
  environmentId: ${ACA_ENV_ID}
  configuration:
    ingress:
      external: true
      targetPort: 3301
    registries:
      - server: ghcr.io
        username: ${GHCR_USERNAME}
        passwordSecretRef: ghcr-password
    secrets:
      - name: ghcr-password
        value: ${GHCR_PASSWORD}
      - name: REDIS_HOST
        value: ${REDIS_HOST}
      - name: REDIS_PORT
        value: ${REDIS_PORT}
      - name: REDIS_PASS
        value: ${REDIS_PASS}
      - name: AUTH_PRIVATE_KEY
        value: ${AUTH_PRIVATE_KEY}
      - name: AUTH_DOMAIN
        value: ${AUTH_DOMAIN}
      - name: THIRDWEB_CLIENT_ID
        value: ${THIRDWEB_CLIENT_ID}
  template:
    containers:
      - name: auth-service
        image: ghcr.io/${GHCR_NAMESPACE}/auth-service:${IMAGE_TAG}
        env:
          - name: PORT
            value: "3301"
          - name: NODE_ENV
            value: "production"
          - name: REDIS_HOST
            secretRef: REDIS_HOST
          - name: REDIS_PORT
            secretRef: REDIS_PORT
          - name: REDIS_PASS
            secretRef: REDIS_PASS
          - name: AUTH_PRIVATE_KEY
            secretRef: AUTH_PRIVATE_KEY
          - name: AUTH_DOMAIN
            secretRef: AUTH_DOMAIN
          - name: THIRDWEB_CLIENT_ID
            secretRef: THIRDWEB_CLIENT_ID
        resources:
          cpu: 0.5
          memory: 1Gi
    scale:
      minReplicas: 1
      maxReplicas: 10
      rules:
        - name: http-rps
          http:
            metadata:
              concurrentRequests: "60"
