name: lending-service
type: containerapp
location: brazilsouth
properties:
  environmentId: ${ACA_ENV_ID}
  configuration:
    ingress:
      external: false
      targetPort: 3301
    registries:
      - server: ghcr.io
        username: ${GHCR_USERNAME}
        passwordSecretRef: ghcr-password
    secrets:
      - name: ghcr-password
        value: ${GHCR_PASSWORD}
      - name: RPC_URL_AVALANCHE
        value: ${RPC_URL_AVALANCHE}
      - name: RPC_URL_FUJI
        value: ${RPC_URL_FUJI}
      - name: PRIVATE_KEY
        value: ${PRIVATE_KEY}
      - name: WALLET_ADDRESS
        value: ${WALLET_ADDRESS}
      - name: JWT_SECRET
        value: ${JWT_SECRET}
  template:
    containers:
      - name: lending-service
        image: ghcr.io/${GHCR_NAMESPACE}/lending-service:${IMAGE_TAG}
        env:
          - name: PORT
            value: "3301"
          - name: NODE_ENV
            value: "production"
          - name: RPC_URL_AVALANCHE
            secretRef: RPC_URL_AVALANCHE
          - name: RPC_URL_FUJI
            secretRef: RPC_URL_FUJI
          - name: PRIVATE_KEY
            secretRef: PRIVATE_KEY
          - name: WALLET_ADDRESS
            secretRef: WALLET_ADDRESS
          - name: VALIDATION_CONTRACT_ADDRESS
            value: ${VALIDATION_CONTRACT_ADDRESS}
          - name: TRADER_JOE_ROUTER
            value: ${TRADER_JOE_ROUTER}
          - name: TRADER_JOE_FACTORY
            value: ${TRADER_JOE_FACTORY}
          - name: RATE_LIMIT_WINDOW_MS
            value: ${RATE_LIMIT_WINDOW_MS}
          - name: RATE_LIMIT_MAX_REQUESTS
            value: ${RATE_LIMIT_MAX_REQUESTS}
          - name: JWT_SECRET
            secretRef: JWT_SECRET
        resources:
          cpu: 0.5
          memory: 1Gi
    scale:
      minReplicas: 1
      maxReplicas: 5
