#!/bin/bash

# Token Test - Test JWT token from API
# Tests if the token generated by API can be verified

BASE_URL="http://localhost:3004"
API_BASE="$BASE_URL/api/lido"
AUTH_BASE="$API_BASE/auth"
TEST_USER="0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6"

echo "🔍 Token Test - API Generated Token"
echo "===================================="

# Step 1: Get token from API
echo "1. Getting token from API..."
LOGIN_RESPONSE=$(curl -s -X POST "$AUTH_BASE/login" \
  -H "Content-Type: application/json" \
  -d "{\"userAddress\": \"$TEST_USER\"}")

echo "$LOGIN_RESPONSE" | jq '.' 2>/dev/null || echo "$LOGIN_RESPONSE"

# Extract token
ACCESS_TOKEN=$(echo "$LOGIN_RESPONSE" | jq -r '.data.accessToken' 2>/dev/null)

if [ "$ACCESS_TOKEN" = "null" ] || [ -z "$ACCESS_TOKEN" ]; then
    echo "❌ Failed to get access token"
    exit 1
fi

echo "✅ Token obtained: ${ACCESS_TOKEN:0:50}..."
echo ""

# Step 2: Test token verification
echo "2. Testing token verification..."
VERIFY_RESPONSE=$(curl -s -X GET "$AUTH_BASE/verify" \
  -H "Authorization: Bearer $ACCESS_TOKEN")

echo "$VERIFY_RESPONSE" | jq '.' 2>/dev/null || echo "$VERIFY_RESPONSE"

if echo "$VERIFY_RESPONSE" | grep -q "success.*true"; then
    echo "✅ Token verification successful"
else
    echo "❌ Token verification failed"
fi
echo ""

# Step 3: Test token info
echo "3. Testing token info..."
TOKEN_INFO_RESPONSE=$(curl -s -X GET "$AUTH_BASE/token-info" \
  -H "Authorization: Bearer $ACCESS_TOKEN")

echo "$TOKEN_INFO_RESPONSE" | jq '.' 2>/dev/null || echo "$TOKEN_INFO_RESPONSE"

if echo "$TOKEN_INFO_RESPONSE" | grep -q "success.*true"; then
    echo "✅ Token info successful"
else
    echo "❌ Token info failed"
fi
echo ""

# Step 4: Test protected endpoint
echo "4. Testing protected endpoint (stake)..."
STAKE_RESPONSE=$(curl -s -X POST "$API_BASE/stake" \
  -H "Authorization: Bearer $ACCESS_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{\"userAddress\": \"$TEST_USER\", \"amount\": \"1.0\"}")

echo "$STAKE_RESPONSE" | jq '.' 2>/dev/null || echo "$STAKE_RESPONSE"

if echo "$STAKE_RESPONSE" | grep -q "success.*true"; then
    echo "✅ Protected endpoint successful"
else
    echo "❌ Protected endpoint failed"
fi
echo ""

echo "🎉 Token test completed!"
