name: Deploy Panorama Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  RG: Core-Deploy
  IMAGE_TAG: ${{ github.sha }}
  GHCR_IMAGE: ghcr.io/${{ github.repository_owner }}/auth-service

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Enable Container Apps extension
        run: az extension add --name containerapp --upgrade

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and push auth-service image
        run: |
          docker build -t $GHCR_IMAGE:${IMAGE_TAG} ./auth-service
          docker push $GHCR_IMAGE:${IMAGE_TAG}

      - name: Authorize container app to pull from GHCR
        run: |
          az containerapp registry set \
            --name auth-service \
            --resource-group $RG \
            --server ghcr.io \
            --username ${{ secrets.GHCR_USERNAME }} \
            --password ${{ secrets.GHCR_PASSWORD }}

      - name: Deploy auth-service
        run: |
          az containerapp update \
            --name auth-service \
            --resource-group $RG \
            --image $GHCR_IMAGE:${IMAGE_TAG}
